/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.eap.pli24.eweather.view;

import javax.swing.JPanel;

/**
 *
 * @author aggelopoulos
 */
public class Central extends javax.swing.JPanel {

    
    private int currentIndex=0;
    
    private ActualWeather actualWeather;
    
    private ForecastWeather forecastWeather;
    
    
    /**
     * Creates new form Main
     */
    public Central() {
        initComponents();
        actualWeather =new ActualWeather();
        actualWeather.setBounds(1, 1, 600, 500);
            
        forecastWeather = new ForecastWeather();
        forecastWeather.setBounds(1, 1, 600, 500);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(289, Short.MAX_VALUE))
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        if (currentIndex== 0)
        {
            actualWeather.setBounds(1, 1, 600, 500);
            actualWeather.setVisible(true);
            mainPanel.add(actualWeather);
           mainPanel.revalidate();
           mainPanel.repaint();
            currentIndex =1;
        }
        else if (currentIndex== 1)
        {
                  //dont do anythink  
        }
        
        else if (currentIndex== 2)
        {
            mainPanel.remove(forecastWeather);
            actualWeather.setBounds(1, 1, 600, 500);
            actualWeather.setVisible(true);
            mainPanel.add(actualWeather);
            mainPanel.revalidate();
           mainPanel.repaint(); 
            currentIndex =1;    
        }
        
        
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
        if (currentIndex== 0)
        {
            
            forecastWeather.setBounds(1, 1, 600, 500);
            forecastWeather.setVisible(true);
            mainPanel.add(forecastWeather);
            mainPanel.revalidate();
            mainPanel.repaint();
            currentIndex =2;
        }
        else if (currentIndex== 1)
        {
            mainPanel.remove(actualWeather); 
            forecastWeather.setBounds(1, 1, 600, 500);
            forecastWeather.setVisible(true);
            mainPanel.add(forecastWeather);
            mainPanel.revalidate();
            mainPanel.repaint();
           currentIndex =2;
        }
        
        else if (currentIndex== 2)
        {
          //dont do anythink 
        }
         
    }//GEN-LAST:event_jButton2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
